global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'my_app'

  scrape_interval: 10s
  scrape_timeout: 10s
  
    static_configs:
      - targets: ['localhost:9090']